// Generated by Wrangler on Thu Jun 13 2024 21:17:47 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	F1_ASSETS: KVNamespace;
	XATA_API_KEY: string;
	XATA_BRANCH: string;
	XATA_DATABASE_URL: string;
}
