// Generated by Wrangler on Thu May 23 2024 11:17:09 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	F1_ASSETS: KVNamespace;
	XATA_API_KEY: string;
	XATA_BRANCH: string;
	XATA_DATABASE_URL: string;
}
